name: Main CI Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-build:
    name: Call Reusable Workflow
    uses: bell-khanawat/node-template/.github/workflows/node-build-template.yml@main
    with:
      node-version: '20'